// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36kGYej0xr-nUu707tje18e6D-nSZlmw',
    appId: '1:645017406229:web:716576e05b85474ad0b71c',
    messagingSenderId: '645017406229',
    projectId: 'flutterproject5-157d4',
    authDomain: 'flutterproject5-157d4.firebaseapp.com',
    storageBucket: 'flutterproject5-157d4.firebasestorage.app',
    measurementId: 'G-PYJ42JJ7Z5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAVvybnVVFXashKM4K4mXgdIm4g5vcn2U',
    appId: '1:645017406229:ios:cc7409ce38323390d0b71c',
    messagingSenderId: '645017406229',
    projectId: 'flutterproject5-157d4',
    storageBucket: 'flutterproject5-157d4.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAVvybnVVFXashKM4K4mXgdIm4g5vcn2U',
    appId: '1:645017406229:ios:cc7409ce38323390d0b71c',
    messagingSenderId: '645017406229',
    projectId: 'flutterproject5-157d4',
    storageBucket: 'flutterproject5-157d4.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuk4ZDnRbyQQVq3UuwbFL9USaZhCaVwqA',
    appId: '1:645017406229:web:0a4d0ec6264fc722d0b71c',
    messagingSenderId: '645017406229',
    projectId: 'flutterproject5-157d4',
    authDomain: 'flutterproject5-157d4.firebaseapp.com',
    storageBucket: 'flutterproject5-157d4.firebasestorage.app',
    measurementId: 'G-TDEQPRVS0Y',
  );
}
